### ISSUE TITLE
The server websocket method 'bus' should send errors back

### ISSUE THREAD

**Issue by tabman83** [horsemeat/dublin-bus-tracker#15]
Should the client side invoke the `changeParams` method with an invalid combination of `stopId` or `busName`, the server should inform the client accordingly. The client will present an error message to the user and invalidate the current countdown.

A suggestion is to have the server reply with the following object when an error occurs:

```
{
    error: "error message from server"
}
```

The error message may be anything meaningful and will be displayed straight to the client.
Examples are:
- Invalid bus stop ID

We cannot actually state that a particular bus name is invalid for a specified stop as we don't know in advance if the bus name does not exist at all or the Dublin Bus website is not showing that particular bus ride at the moment.

However this could cater for future error messages.

Comments are welcome!

**Comment by peppepetra** [comment]
I propose this: after the user select the stop id, he sees the available routes for that stop. If user enters an invalid stop he will see no available routes.
