### ISSUE TITLE
Options in the client

### ISSUE THREAD

**Issue by lupino3** [horsemeat/dublin-bus-tracker#2]
The client should have an option pane that allows to specify some options (for instance, stops and bus routes to be used once Issue #1 is fixed). The options should be stored client-side and the pane itself should be very discreet, for instance with a very light icon on the top-left corner, that opens a menu similar to Android's NavigationDrawer.

**Comment by tabman83** [comment]
The options menu has been implemented with https://github.com/horsemeat/dublin-bus-tracker/pull/8

**Comment by lupino3** [comment]
We have the changeParams request (commit 132524f89eef1b3514b2e6807755e4c47e427497).
