### ISSUE TITLE
Enhance the server data response

### ISSUE THREAD

**Issue by tabman83** [horsemeat/dublin-bus-tracker#7]
The server should return an array of objects.

Each element of the array should be objects like this:

```
{
    busName: "41c", // all lowercase
    stopId: "3605",
    expectedTime: "2015-03-30T22:44:30.652Z", // ISO8601
    expectedWait: "PT22M" // ISO8601
}
```

busName and stopId might be useful for future improvements like multiple bus/stop monitorings.

The `expectedWait` will be calulated server side by moment.js which takes care of the ISO8601 serialization as well.
The `expectedTime` might be useful to just display the time of arrival when the awaiting time exceeds a certain amount.

Comments are welcome.

**Comment by lupino3** [comment]
Sounds good!
